# -*- coding: utf-8 -*-
"""Quiz Application

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ABgjXFDYihIV1n8W5pH4ii2mr-n4FPkW
"""

from IPython.display import HTML

HTML("""
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Quiz Application</title>

<style>
body{
    font-family: Arial, sans-serif;
    background: linear-gradient(135deg,#6a11cb,#2575fc);
    padding:20px;
}

.container{
    max-width:700px;
    margin:auto;
    background:white;
    padding:20px;
    border-radius:15px;
}

h1{
    text-align:center;
    color:#6a11cb;
}

.question{
    margin:20px 0;
}

button{
    background:#2575fc;
    color:white;
    border:none;
    padding:10px 20px;
    border-radius:5px;
    cursor:pointer;
}

button:hover{
    background:#6a11cb;
}

#result{
    margin-top:20px;
    font-size:22px;
    font-weight:bold;
    text-align:center;
}
</style>
</head>

<body>

<div class="container">

<h1>Quiz Application</h1>

<div class="question">
<p>1. What does HTML stand for?</p>
<input type="radio" name="q1" value="a"> Hyper Text Markup Language<br>
<input type="radio" name="q1" value="b"> High Tech Modern Language<br>
<input type="radio" name="q1" value="c"> Hyper Transfer Machine Language<br>
</div>

<div class="question">
<p>2. Which language is used for styling web pages?</p>
<input type="radio" name="q2" value="a"> HTML<br>
<input type="radio" name="q2" value="b"> CSS<br>
<input type="radio" name="q2" value="c"> Python<br>
</div>

<div class="question">
<p>3. Which company developed JavaScript?</p>
<input type="radio" name="q3" value="a"> Microsoft<br>
<input type="radio" name="q3" value="b"> Netscape<br>
<input type="radio" name="q3" value="c"> Google<br>
</div>

<div class="question">
<p>4. Which HTML tag creates the largest heading?</p>
<input type="radio" name="q4" value="a"> h6<br>
<input type="radio" name="q4" value="b"> h3<br>
<input type="radio" name="q4" value="c"> h1<br>
</div>

<div class="question">
<p>5. Which symbol is used for ID selector in CSS?</p>
<input type="radio" name="q5" value="a"> #<br>
<input type="radio" name="q5" value="b"> .<br>
<input type="radio" name="q5" value="c"> *<br>
</div>

<button onclick="checkQuiz()">Submit Quiz</button>

<div id="result"></div>

</div>

<script>
function checkQuiz(){

let score = 0;

if(document.querySelector('input[name="q1"]:checked')?.value==="a") score++;
if(document.querySelector('input[name="q2"]:checked')?.value==="b") score++;
if(document.querySelector('input[name="q3"]:checked')?.value==="b") score++;
if(document.querySelector('input[name="q4"]:checked')?.value==="c") score++;
if(document.querySelector('input[name="q5"]:checked')?.value==="a") score++;

document.getElementById("result").innerHTML =
"🎉 Your Score: " + score + " / 5";
}
</script>

</body>
</html>
""")